server:
  port: 8761

eureka:
  client:
#    缓存清单的更新时间(30秒获取一次服务列表)
    registry-fetch-interval-seconds: 10
    register-with-eureka: true
#    抓取注册的服务
    fetch-registry: true
  server:
    wait-time-in-ms-when-sync-empty: 0
  instance:
#   心跳频率（30向服务器发送一次心跳）
    lease-renewal-interval-in-seconds: 10
#    服务超时（服务停止90秒后 剔除出服务列表）
    lease-expiration-duration-in-seconds: 20

