server:
  port: 8888


#会在所有actuator 提供的端点前一个指定前缀 对
#应在eureka检查端点上也需要做出相应配置
management:
#  context-path: /admin
# endpoint 访问认证
  security:
      enabled: true



#配置多个注册中心 逗号分隔
eureka:
  client:
      service-url:
            defaultZone: http://discovery:8761/eureka
  instance:
    hostname: configserver
#    non-secure-port: 80
#    lease-renewal-interval-in-seconds: 10
#    注册中心健康状况页 http://configserver:8888/health
    health-check-url-path: ${management.context-path}/health
#    注册中心状态页 http://configserver:8888/health
    status-page-url-path: ${management.context-path}/info
    prefer-ip-address: true


#config server repository
spring:
#  从本地读取配置（不推荐）
#  profiles:
#    active: native
  cloud:
    config:
      server:
#      远程配置文件路径
        git:
          uri: https://github.com/looper123/config-repository-master.git
          search-paths: config-child
          username: m17701848923@163.com
          password: lzp19920312
#          使用了git或者svn 后再本地的备份文件
#          windows下的绝对路径需要用///来分隔（by 官网）
          basedir: D:///idea workspace///spring-cloud-local-bak
#         本地配置文件路径(需要打开读取本地配置spring.profiles.active= native)
#        native:
#          search-locations: D:///idea workspace///spring-cloud-local-bak

#         配置库健康监测
#        health:
#          repositories:
#              check:
#                name: didispace
##                label:
#                profiles: dev
#        无法被客户端修改 （可以用来配置客户端的公共属性 或者默认属性）
#        overrides:
#           name: customerName
#           from: customerFrom

#          git远程配置文件命名规则
#          • /{application}/{profile} [/{label}]
#          • {application}一{profile}. yml
#          • /{label}/{application}-{profile}.yml
#          • /{application}-{profile}.properties
#          • /{label}/{application}-{profile}.properties


#spring-sercurity
security:
  user:
#   需要在对应客户端添加用户 密码信息 否则无法访问config server服务端
    name: admin
    password: admin
  basic:
    enabled: true



encrypt:
#  对称性加密 本地需要先安装curl
# 执行 curl localhost:8888/encrypt -d looper123
#得到 looper123 加密后 543f65989a17283dedc051e7646c0bf0e590fdb6f26e8e0b3f95d7740f78d63ef88b151b05ce7e7943b22df245dd98a5
# 在执行 curl localhost:8888/decrypt -d  543f65989a17283dedc051e7646c0bf0e590fdb6f26e8e0b3f95d7740f78d63ef88b151b05ce7e7943b22df245dd98a5
# 可以得到解密后的原文 looper123

#  key: '{cipher}543f65989a17283dedc051e7646c0bf0e590fdb6f26e8e0b3f95d7740f78d63ef88b151b05ce7e7943b22df245dd98a5'

# 非对称性加密
#一次性生成keystore文件 并且设置所有参数 密码、存活时间。。。
#keytool -genkeypair -alias config-server -keyalg RSA -dname "CN=zhaiyongchao, OU=company, O=organization,
#L=city, ST=province,C=china" -keypass 222222  -keystore config-server.keystore -storepass 111111  -validity 365
  keyStore:
    location: classpath:config-server.keystore
    password: 111111
    alias: config-server
    secret: 222222

#  fail-on-error: true


#  oauth2:
#    client:
#      access-token-uri: ${vcap.services.${PREFIX:}sso.credentials.tokenUri:}
#      user-authorization-uri: ${vcap.services.${PREFIX:}sso.credentials.authorizationUri:}
#      client-id: ${vcap.services.${PREFIX:}sso.credentials.clientId:}
#      client-secret: ${vcap.services.${PREFIX:}sso.credentials.clientSecret:}
#    resource:
#      token-info-uri: ${vcap.services.${OAUTH2_RESOURCE_SERVICEID:${oauth2.resource.serviceId:sso}}.credentials.tokenInfoUri:}
#      service-id: ${PREFIX:}resource






