server:
  port: 8888

#会在所有actuator 提供的端点前一个指定前缀 对
#应在eureka检查端点上也需要做出相应配置
management:
  context-path: /admin
  security:
    enabled: true

#配置多个注册中心 逗号分隔
eureka:
  client:
      service-url:
            defaultZone: http://discovery:8761/eureka
  instance:
    hostname: configserver
#    non-secure-port: 80
#    lease-renewal-interval-in-seconds: 10
#    注册中心健康状况页 http://configserver:8888/health
    health-check-url-path: ${management.context-path}/health
#    注册中心状态页 http://configserver:8888/health
    status-page-url-path: ${management.context-path}/info
    prefer-ip-address: true


#config server repository
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/looper123/config-repository-master.git
          search-paths: config-repository
          username: m17701848923@163.com
          password: lzp19920312
#spring-sercurity
#security:
#  basic:
#    enabled: false
#  oauth2:
#    client:
#      access-token-uri: ${vcap.services.${PREFIX:}sso.credentials.tokenUri:}
#      user-authorization-uri: ${vcap.services.${PREFIX:}sso.credentials.authorizationUri:}
#      client-id: ${vcap.services.${PREFIX:}sso.credentials.clientId:}
#      client-secret: ${vcap.services.${PREFIX:}sso.credentials.clientSecret:}
#    resource:
#      token-info-uri: ${vcap.services.${OAUTH2_RESOURCE_SERVICEID:${oauth2.resource.serviceId:sso}}.credentials.tokenInfoUri:}
#      service-id: ${PREFIX:}resource

management.security.enabled: false






