server:
  port: 8088

eureka:
  instance:
    hostname: sleuth
    instance-id: ${spring.application.name}:${random.int[10000,19999]}
    #同一主机上 不同端口多实例 说明instanceID才是各个服务的唯一标识 去注册中心获取服务时也是通过instanceId来获取
    prefer-ip-address: true
#    non-secure-port: 80
  client:
     service-url:
      defaultZone: http://discovery:8761/eureka



