server:
  port: 8084

#通过网关的访问路径http://localhost:8084/api-a/hello
#ant 风格 ?任意单个字符 *匹配任数量的字符  **匹配任意数量的字符 支持多级目录
# yml文件下实现有序的路由规则 （即如果同时匹配了api-a 和api-b 会优先进入api-a中 而不会进入api-b 因为路由规则是线性加载的
#底层保存在linkedhashmap中 而properties文件无法保证有序）
zuul:
  routes:
    api-a:
#    推荐配置 （因为zuul本身实现了ribbon负载均衡和hystrix的断路器功能，path+serviceId的配置保证网关的健壮和稳定）
#   zuul可以像ribbon和hystrix中一样来配置负载均衡和熔断策略（ribbon的超时时间要 < hystrix 熔断后无法触发重试）
#   关闭该路由的重试策略
#      retryable: false
      path: /api-a/**
#      把所有匹配/api-a/**的请求转发到指定serviceId的服务上
      serviceId: sample
#     把所有匹配/api-a/**的请求转发到指定url的服务上
#      注意 ！！当使用 path+url组合来配置路由时 没有负载均衡和断路器保护（路由转发的请求不会使用HystrixCommand来包装）
#      url: http://localhost:8081/hello
    api-b:
      path: /api-b/**
      serviceId: feign-consumer


#cookie在zuul网关中默认是不允许传递的
#推荐方法1 指定路由开启自定义头信息
#    api-c:
#      customerSensitiveHeaders: true
#推荐方法2 指定路由头信息全开启 为空会覆盖系统默认设置
#      api-c:
#        sensitiveHeaders:

#页面发送的重定向请求不会经过网关？？
#add-host-header: true


# 等价于
#zuul:
#  routes:s
#    sample: /sample/**
#    feign-consumer: /feign-consumer/**


#  所有的服务都不创建路由
#  ignored-services: *
#   细化不需要创建路由的颗粒度
#    ignored-patterns: /**/hello/**


#  全局路由前缀
#  prefix: /api

eureka:
  instance:
    hostname: api-zuul
    instance-id: ${spring.application.name}:${random.int[10000,19999]}
    #同一主机上 不同端口多实例 说明instanceID才是各个服务的唯一标识 去注册中心获取服务时也是通过instanceId来获取
#    如果默认（false） 当服务向eureka注册时会以sample:8081的形式注册到loadBalance中(隐藏ip)
#    为true时 会以真实ip  127.0.0.1：8081的形式注册到loadbalance中
    prefer-ip-address: true
  client:
     service-url:
         defaultZone: http://discovery:8761/eureka




